//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPP_Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glumi
    {
        public int GlumiID { get; set; }
        public int JMBG { get; set; }
        public int PredstavaID { get; set; }
    
        public virtual Glumac Glumac { get; set; }
        public virtual Predstava Predstava { get; set; }
    }
}
