//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPP_Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predstava
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Predstava()
        {
            this.Glumi = new HashSet<Glumi>();
            this.StavkaRepertoara = new HashSet<StavkaRepertoara>();
        }
    
        public int PredstavaID { get; set; }
        public string NazivPredstave { get; set; }
        public string Zanr { get; set; }
        public int Duzina { get; set; }
        public string Scenarista { get; set; }
        public string Reditelj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Glumi> Glumi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaRepertoara> StavkaRepertoara { get; set; }
    }
}
