//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPP_Pozoriste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repertoar
    {
        public int RepertoarID { get; set; }
        public int StavkaID { get; set; }
        public int MesecID { get; set; }
    
        public virtual Mesec Mesec { get; set; }
        public virtual StavkaRepertoara StavkaRepertoara { get; set; }
    }
}
